// <auto-generated />
namespace External_Login_Identity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Dbmigration08042020at931am : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dbmigration08042020at931am));
        
        string IMigrationMetadata.Id
        {
            get { return "202004080402000_Dbmigration08042020at931am"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
